Repository hemkan/MotorEase, pull requests merged in 2024-04, with the labels that each got.

#11 Identify interactive elements and display
  Code/MotorEase.py
  Code/detectors/Visual/TouchTarget.py
  MotorEase.py
Labels: enhancement

#17 Display Violating Elements (if any)
  Code/MotorEase.py
  Code/detectors/Visual/TouchTarget.py
  MotorEase.py
Labels: enhancement

#20 Added a Local Image Build to MotorEase
  .gitignore
  Code/Dockerfile
  Code/MotorEase.py
  Code/detectors/Visual/IconDistance.py
  Code/detectors/Visual/TouchTarget.py
  Code/requirements.txt
  README.md
Labels: bug, documentation, enhancement

#21 Fix bug for getting elements
  Code/detectors/Visual/TouchTarget.py
Labels: bug

#23 Translate violating components from Android Syntax to English
  Code/detectors/Visual/TouchTarget.py
Labels: enhancement

#24 Translate interactive components from Android Syntax to English
  Code/detectors/Visual/TouchTarget.py
Labels: enhancement
